### ISSUE TITLE
Browser crash on loading video/audio of duration around 2 hours

### ISSUE THREAD

**Issue by bugcoder** [zhw2590582/WFPlayer#39]
We are using mp3 file of 7.6 MB with duration around 2 hours. WFPlayer is working fine with less duration audio files and not using much memory. However, whenever we are using audio with large duration such as 2 hours, it's consuming around 4 GB of memory and keep on using more memory and browser get crash eventually.

We are using below code:

```
var wf = new WFPlayer({
        container: document.querySelector('#waveform')
    });

//fetching audio with duration more than 2 hours
    fetch('example.com/mp3')
        .then((res) => res.arrayBuffer())
        .then((arrayBuffer) => {
            const uint8 = new Uint8Array(arrayBuffer);
            wf.load(uint8);
        });
```

Memory Usage:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5323555/208996964-dee6289a-c077-4f9b-bc1b-3ad98f882c3e.png">

- [ ] We are looking to use audio files with large duration with WFPlayer.

**Comment by yuguaa** [comment]
This problem also occurs in the project. When decoding, the bit rate is too high, resulting in too much audio sample data, and too little rendering waveform will cause problems. After consideration, we decided to cancel the rendering of the waveform. Based on this, we changed this package., disabled the decoder, other functions are normal, but no waveform diagram

**Comment by ExtReMLapin** [comment]
You don't need to @yuguaa 

You can use ffmpeg WASM to convert the file in browser !



```js
```vue
   async videoOrAudioToMP3(ffmpegInstance, videoOrAudioFile) {
      // Prepare the files for ffmpeg.wasm
      //remove all spaces and special characters from the file name
      const videoOrAudioFileName = videoOrAudioFile.name.replace(/[^a-zA-Z0-9.]/g, "");
      const outputFileName = "output_" + videoOrAudioFileName + ".mp3";

      ffmpegInstance.FS("writeFile", videoOrAudioFileName, new Uint8Array(await videoOrAudioFile.arrayBuffer()));

      // Run FFmpeg command to replace the audio track
      this.conversionProgress = 0
      //const self = this;
      await ffmpegInstance.run(
        "-i",
        videoOrAudioFileName,
        "-vn",
        "-acodec",
        "libmp3lame",
        "-ac",
        "1",
        "-ar",
        "16000",
        "-ab",
        "128k",
        outputFileName
      );

      // Read the output file and return it as a File object
      const outputFileBuffer = ffmpegInstance.FS("readFile", outputFileName);
      const outputFileBlob = new Blob([outputFileBuffer.buffer], { type: "audio/mpeg" });
      const outputFile = new File([outputFileBlob], outputFileName, { type: "audio/mpeg" });
      this.conversionProgress = 100


      return outputFile;
    },
``````

**Comment by yuguaa** [comment]
> 

Thank you for your response. I appreciate it. I understand that I can do it this way. Moreover, I manually modified the `drawWave` method and simulated audio data using video subtitles' data. The result is that when I simulate a lower bitrate, the project runs smoothly. This might be because my practice project is based on the open-source project Subplayer by the author. However, when rendering the `wfplayer` with simulated data, it still crashes due to the large amount of data. It seems that I need to do more optimization for the React project. In any case, I appreciate your response.

worker.js
![image](https://github.com/zhw2590582/WFPlayer/assets/58333667/66d30cdb-88a4-41d3-a0de-8c40bf022a0b)
![image](https://github.com/zhw2590582/WFPlayer/assets/58333667/52b295d0-f9c0-4f0f-9d13-75039f9ed736)
index.js
![image](https://github.com/zhw2590582/WFPlayer/assets/58333667/113fc60d-a881-4a0d-85e0-eb6006191a17)
![image](https://github.com/zhw2590582/WFPlayer/assets/58333667/e5e7fa78-c2c6-4528-9cc7-0b4c5c75d5e1)

**Comment by ExtReMLapin** [comment]
I wish I was this naturally polite and friendly as you are
